language: java
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAZJRSI6Y2NNKAM4ML
  secret_access_key: FcEx7p18/Mhm35Dc6b38bHZd8+/7zY1+vj0pcVmkL1sobN/t50P99uRdilgJRzBjyEj+7Z4G+OE+4aolnAiS2OIdkObK1g3wa3KQoNjJn/B9KaVpJCAjvxk+gkEM1DgsixqLto1F6sHp9OKprQuoULXXxoZ0SqM9W31VSmEvPzq5qcbjc0jZzYjJzKyXlIWr7+TJs0wOJS1oDQKr6wwafPiVGT1RD9ovoGMsvsW0AFIw8ayWmXxfssknFhoG3BfISGYFOLMRzzsXG/4QvdbKvKLLb6O8iSGWcuB5CSDj7eBuP/uZQT4Bqdc8wYJO7oMajTHPZh8vp50/eBEW4G4MT4QQAnhuRxZHQH3NFFdgzhZTKr52RouP9BfztA+ceEtYhdp+tQe4QIGpddx3K2rsfzg70mkVTMytgcLGUxKYcnO5ExUZKBS6lSSZ+eFZqhj//QpKVy6HrCf922kT1vBhcngMPAdpYZQBFbjEg6wR7acINt168tEtcfIFwBuWEcPbj0nIQ7zgU+gDWONr9AOqJUUz1F8FSAePiC6mpTxtOK9AJjLgEz1pj8uj6PhIUXOEKhdEoE9JIzAFWrtBnC4FrYO++pi8KBopUdu9YQsnsmuiufKjRMh4d/rVHSyScGw3BhqqsrVDuTod0fKhKGHrtu4QUcpD4FlfadoLGvj79H8=
  region: us-west-1
  app: graphattan
  env: graphattan-env-mk2
  on:
    repo: erchiggins/graphattan
  bucket: elasticbeanstalk-us-west-1-638981830196