language: java
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAZJRSI6Y2AIYF4HST
  secret_access_key:
    secure: zoRPdo23Md1+CDkxuFQZVPwGyb3aFh8frujjR9zGl/nJuW8A6r+lhLkCqc80KYJNns8pAeOVPbI6Q8lGGibcDMmqep+7VWVVSXbbBXzV0W2U+pFaHc5ip0BPVzCV9DQau+LbpG432h2xLQjMR+IQFzMs2DBNrXQVcuRN47kkgaELkpaDq4nayS7zUHxvgIZIg/1uSSmwXtNQAYs88qBpPsnnW8hpOg1VDtM2gXNvM0oL8VstbFrL+XOSYJnCRdxrpdOSPwsb933oVX4abg3cq5N98uLKqCuZKzeJwa21Y02YfFJUtrbt7jzn0B5G40wZCdRFd6mIxFXitVlYsiPILYUUDrX+iLFWtPZqkPLme5N7K4YxDDaq9qIh0NMjmFaNovk3y4pddNIBFTrkvajrMXZkbLyZtHc8gT+ZSYWdFIeK4tGgy4Z4pThhK/dJBiZ15ljmIgcwwSAN7dBykCh6sCWSzypWxx1y0QYOF5ha/uVl/XGO4jhiH4jv+lvLueDR76kcAnQGldOGYH/PdZqEHvo3+Y/A16Cz5T4Urpm5PrhHxZLL1Ad3AgvIFB8A+VR7mvmS7oCPcHtKibo39W0zni5SaKcFdVtXgaicHKeMKVcrZ7EsVThyYyn182HXGqB6I9OfYPPL+zj9yqF6d0HphE5TMfiGxCVs2eYCdQwwdZI=
  region: us-west-1
  app: graphattan
  env: graphattan-env-mk2
  on:
    repo: erchiggins/graphattan
  bucket: elasticbeanstalk-us-west-1-638981830196