language: java

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAZJRSI6Y2NNKAM4ML
  secret_access_key:
    secure: "YzEjkD+tHnqSNhIXGMtPPmQFt/W84wpYGzSDE+uTi2XZxHGNNlSyw4DchmHvud/HJvryyjaVXICsIF5VXPPvJaGpRNvRtLsYuCDr5o5NpzpC1uvI1uALRBbUv5gFe6H4RiTrJwt9a3eMqwmuz0mRJckeRYvDze4gpdpqZcUom4KzLYKpocifrFUWWpz/Z4QfnNOPTnXn7mUFYxdtYxzthY/NnLhVnSVALrR35U2FyoIw6QECjrQ8wdbcO1PK/ekne1lTONTxLM5eahDrCEsIQZos8yxuunvAJgwomClWQkr5dprQuETgIDOLKcLLJVnSI0tSrjBh0hrTLwt6d3E9CI2RObnnwO0jnPMdBU7Ja8ruCcnneOLomNbrFu4dY+wsSnYo79ha5oApTbBEl3xK6rtuYoGRjNgo2fpZVpXQNeSCvGDPTEGmO2Nof0Qrevs8p+nQA8LKOkhoN4mH/lO54wTMkydNeayufP1jtB/yxVjbSDfUIOImLrHorwW4XXra5VlylSecobNdWOC+TAF2P2mmQkxiwvi4hUnM9GwgaU6NzrWqr0Y8DYcy4fUWezCmRQ0xWS41Ph41I25vf27AV7WhzCYp9E+U7UZeTBVXQSf6yhk1gUT3yGb1Vkr8iwAJDgwGCQq09PR12BQmq+/FvdHIT9SV1TpDDK1sV1i3iuU="
  region: "us-west-1"
  app: graphattan
  env: graphattan-env-mk2
  bucket: elasticbeanstalk-us-west-1-638981830196
